### ISSUE TITLE
System Crashes After Aborted Txn

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#709] opened 2017-06-30 16:19 UTC
The system will crash if you try to start another txn after the previous txn aborted:

**First create the table**
```
postgres=# CREATE TABLE foo (id INT PRIMARY KEY);
CREATE TABLE foo (id INT PRIMARY KEY) 0
```

**Then start a txn that will attempt to insert the same key twice. The second insert will (correctly) fail, causing the whole txn to abort**
``` 
postgres=# BEGIN;
BEGIN
postgres=# INSERT INTO foo VALUES (1);
INSERT INTO foo VALUES (1) 1
postgres=# SELECT * FROM foo;
 id 
----
  1
(1 row)

postgres=# INSERT INTO foo VALUES (1);
INSERT INTO foo VALUES (1) 0
postgres=# SELECT * FROM foo;
SELECT * FROM foo 0
postgres=# COMMIT;
COMMIT
postgres=# SELECT * FROM foo;
 id 
----
(0 rows)
```

**But now if you try to insert that same key again, the system crashes**
```
postgres=# BEGIN;
BEGIN
postgres=# SELECT * FROM foo;
 id 
----
(0 rows)

postgres=# INSERT INTO foo VALUES (1);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Here is the error from the server:
```
peloton: /home/pavlo/Documents/Peloton/Github/peloton-master/src/index/bwtree_index.cpp:106: bool peloton::index::BWTreeIndex<KeyType, ValueType, KeyComparator, KeyEqualityChecker, KeyHashFunc, ValueEqualityChecker, ValueHashFunc>::CondInsertEntry(const peloton::storage::Tuple*, peloton::ItemPointer*, std::function<bool(const void*)>) [with KeyType = peloton::index::CompactIntsKey<1ul>; ValueType = peloton::ItemPointer*; KeyComparator = peloton::index::CompactIntsComparator<1ul>; KeyEqualityChecker = peloton::index::CompactIntsEqualityChecker<1ul>; KeyHashFunc = peloton::index::CompactIntsHasher<1ul>; ValueEqualityChecker = peloton::ItemPointerComparator; ValueHashFunc = peloton::ItemPointerHashFunc]: Assertion `ret == true' failed.
```

**Comment by yingjunwu** [comment] 2017-07-03 08:47
I have checked the code and found that the major problem is that bwtree may not handle conditional insert correctly. When a client inserts a duplicated tuple into the bwtree, bwtree will find that the predicate passed to the `CondInsertEntry()` function is not satisfied. However, instead of returning the result back to the transaction layer, bwtree directly triggers an assertion failure. Please check the code between lines 104-109 at https://github.com/cmu-db/peloton/blob/master/src/index/bwtree_index.cpp.

**Comment by wangziqi2013** [comment] 2017-07-03 21:15
Commenting out the failing assertion will do the trick

This is caused by the original design not checking the return value inside `CondInsertEntry()` After we have switched to a newer BwTree in January this year, part of the logic for checking key duplications were moved, and the failing assertion does not hold anymore.

**Comment by yingjunwu** [comment] 2017-07-04 02:13
Then @wangziqi2013 could send a PR to fix this bug.

**Comment by apavlo** [comment] 2017-07-04 03:32
It's more than just commenting it out. We need a test case to prove that it actually works.

**Comment by apavlo** [comment] 2017-07-09 15:04
@wangziqi2013 I commented out line 106 in 'bwtree_index.cpp' as you suggested. It no longer crashes but it still not correct. It still does not let you insert a tuple with the same key:

**First txn that fails correctly when trying to insert the same key twice:**
```
postgres=# CREATE TABLE foo (id INT PRIMARY KEY);
CREATE TABLE foo (id INT PRIMARY KEY) 0
postgres=# BEGIN;
BEGIN
postgres=# INSERT INTO foo VALUES (1);
INSERT INTO foo VALUES (1) 1
postgres=# SELECT * FROM foo;
 id 
----
  1
(1 row)

postgres=# INSERT INTO foo VALUES (1);
INSERT INTO foo VALUES (1) 0
postgres=# SELECT * FROM foo;
SELECT * FROM foo 0
postgres=# COMMIT;
COMMIT
```

**Now the second txn tries to insert the same tuple into an empty table but it fails:**
```
postgres=# SELECT * FROM foo;
 id 
----
(0 rows)

postgres=# INSERT INTO foo VALUES (1);
INSERT INTO foo VALUES (1) 0
postgres=# SELECT * FROM foo;
 id 
----
(0 rows)
```

**Comment by wangziqi2013** [comment] 2017-07-13 01:34
@apavlo It looks like something unusual is happening inside the predicate that judges whether a key already exists or not. I ran the above command, and enabled BwTree to print out steps in delta chain traversal, here is the output (removed the LOG_INFO header for clarity; bold texts are command, and everything beneath the command are the output of that command; everything after "#" are my own comments):

**BEGIN;
INSERT INTO foo VALUES (1);**
```
INFO  - Starting delta chain traversal      # First insertion into the table
INFO  - Leaf type; size = 0                 # This is normal because the index is empty
INFO  - Predicate satis = 0; ret = 1        # Hit the leaf node, it is empty, so insertion happens
```
**INSERT INTO foo VALUES (1);**
```
INFO  - Starting delta chain traversal      # Starting the second traversal for the insertion
INFO  - Leaf insert delta type              # Since the last insertion succeeds, there is a leaf
                                            # insert delta, and now we hit that delta, the predicate
                                            # checks the item pointer, finding out that it is a duplicated key
INFO  - Insert delta predicate is true      # See above
INFO  - Predicate satis = 1; ret = 0        # So predicate it satisfied and we know it is a key duplication
                                            # "ret = 0" means no actual insertion into the tree happens
```
**COMMIT;**
**SELECT * FROM foo;**
```
INFO  - 1                                   # This is the output for the SELECT statement above
```
**INSERT INTO foo VALUES (1);**           # Here is where the problem arises
```
INFO  - Starting delta chain traversal      # Starting a leaf delta chain traversal
INFO  - Leaf insert delta type              # Saw the leaf insert delta. This is the only delta in the index
                                            # which was appended on the first INSERT statement
INFO  - Insert delta value already exists   # *** HERE IS THE PROBLEM ***
                                            # The predicate did not return true, which means there is no key    
                                            # duplication. This is expected because the previous transaction
                                            # aborted. However, the key-value pair remain a valid entry in the
                                            # index, and we do not allow adding the same entry twice. Thus
                                            # here the index rejected the insert operation (rather than the 
                                            # MVCC layer).
                                            # The root cause is that the new transaction tried to insert the same item 
                                            # pointer object as the one previously aborted. The index will of course
                                            # reject the second insert operation, because even though the predicate
                                            # thinks it is not a duplicated key, it violates the index consistency rule.
INFO  - Predicate satis = 0; ret = 0
```

**Comment by yingjunwu** [comment] 2017-07-24 05:35
fixed by #764

**Comment by pmenon** [comment] 2017-07-27 12:51
Let's not close the issue until the PR has been tested and merged in.

**Comment by yingjunwu** [comment] 2017-08-11 03:22
This issue can be closed as the PR has been merged and tested.

**Closed by yingjunwu** 2017-08-11 03:22 UTC
Labels: bug
