### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by bluealert** [cmu-db/peloton#812] opened 2017-09-26 02:56 UTC
I run `make check` on macOS 10.12.6 :

```
➜  build make check
Scanning dependencies of target peloton-test-common
[  1%] Building CXX object test/CMakeFiles/peloton-test-common.dir/__/third_party/gmock/gmock-gtest-all.cc.o
[  1%] Building CXX object test/CMakeFiles/peloton-test-common.dir/__/third_party/gmock/gmock_main.cc.o
In file included from /Users/tao/Cpp/peloton-master/third_party/gmock/gmock_main.cc:33:
/Users/tao/Cpp/peloton-master/third_party/gmock/gmock/gmock.h:893:27: error: use of undeclared identifier 'kReference'
    return type(array, N, kReference);
                          ^
/Users/tao/Cpp/peloton-master/third_party/gmock/gmock/gmock.h:900:27: error: use of undeclared identifier 'kCopy'; did you mean
      'Copy'?
    return type(array, N, kCopy);
                          ^~~~~
                          Copy
/Users/tao/Cpp/peloton-master/third_party/gmock/gmock/gmock.h:896:15: note: 'Copy' declared here
  static type Copy(const Element (&array)[N]) {
              ^
/Users/tao/Cpp/peloton-master/third_party/gmock/gmock/gmock.h:918:47: error: use of undeclared identifier 'kReference'
    return type(get<0>(array), get<1>(array), kReference);
                                              ^
/Users/tao/Cpp/peloton-master/third_party/gmock/gmock/gmock.h:922:47: error: use of undeclared identifier 'kCopy'; did you mean
      'Copy'?
    return type(get<0>(array), get<1>(array), kCopy);
                                              ^~~~~
                                              Copy
/Users/tao/Cpp/peloton-master/third_party/gmock/gmock/gmock.h:920:15: note: 'Copy' declared here
  static type Copy(const ::std::tr1::tuple<ElementPointer, Size>& array) {
              ^
4 errors generated.
make[3]: *** [test/CMakeFiles/peloton-test-common.dir/__/third_party/gmock/gmock_main.cc.o] Error 1
make[2]: *** [test/CMakeFiles/peloton-test-common.dir/all] Error 2
make[1]: *** [test/CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2
```

I found the definition of [kReference](https://github.com/cmu-db/peloton/blob/master/third_party/gmock/gtest/gtest.h#L7910) and `kCopy` is in `gtest/gtest.h.

**Comment by seojungmin** [comment] 2017-09-26 04:00
Please list up what you have done before make check, and their results.  This seems to be some compilation configuration issue from my quick web search.  My OSX 10.12.5 works fine, and yours should work if you followed the typical build instructions.

**Comment by PauloAmora** [comment] 2017-09-26 04:07
I'd like to add that if you could list your compiler/version it helps a lot.

Em 26 de set de 2017 00:00, "Jungmin Seo" <notifications@github.com>
escreveu:

**Comment by bluealert** [comment] 2017-09-26 04:07
Before I run `make check`, I run `cmake ..` and `make -j 4` in directory named build. The two commands all run successfully.

```
cmake -DCMAKE_BUILD_TYPE=Debug ..
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- The C compiler identification is AppleClang 8.0.0.8000042
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
INFO Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

-- Unknown compiler. Version info:
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Selected compiler
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   chrono
--   date_time
--   atomic
-- Found GFlags: /usr/local/include
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
-- Found Protobuf: /usr/local/lib/libprotobuf.dylib (found version "3.4.0")
-- Found PROTOBUF Compiler: /Users/tao/anaconda3/bin/protoc
-- Found libevent (include: /usr/local/include, library: /usr/local/lib/libevent.dylib)
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.13") found components:  doxygen dot
-- Found JeMalloc: /usr/local/lib/libjemalloc.dylib
-- Found jemalloc (include: , library: /usr/local/lib/libjemalloc.dylib)
-- Found LLVM 3.7.1
-- Found PythonInterp: /Users/tao/anaconda3/bin/python (found version "3.6.1")
-- Performing Test COMPILER_SUPPORTS_CXX1Y
-- Performing Test COMPILER_SUPPORTS_CXX1Y - Success
-- Found Git: /usr/local/bin/git (found version "2.14.1")
--
-- ******************* Peloton Configuration Summary *******************
-- General:
--   Version           :   0.0.5
--   Git               :   unknown
--   System            :   Darwin
--   Compiler          :   /Library/Developer/CommandLineTools/usr/bin/c++ ( )
--   Release CXX flags :   -O3 -DNDEBUG -std=c++1y -D__PELOTONFILE__='"$(subst /Users/tao/Cpp/peloton-master/,,$(abspath $<))"' -fcolor-diagnostics -fPIC -Wall -Wextra -Werror -mcx16 -Wno-invalid-offsetof -march=native -Wno-tautological-undefined-compare -Wno-unused-private-field -Wno-braced-scalar-init -Wno-constant-conversion -Wno-potentially-evaluated-expression -Wno-infinite-recursion -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/usr/local/opt/openssl/include -Wno-strict-aliasing
--   Debug CXX flags   :   -g -O0 -ggdb -fno-omit-frame-pointer -fno-optimize-sibling-calls -std=c++1y -D__PELOTONFILE__='"$(subst /Users/tao/Cpp/peloton-master/,,$(abspath $<))"' -fcolor-diagnostics -fPIC -Wall -Wextra -Werror -mcx16 -Wno-invalid-offsetof -march=native -Wno-tautological-undefined-compare -Wno-unused-private-field -Wno-braced-scalar-init -Wno-constant-conversion -Wno-potentially-evaluated-expression -Wno-infinite-recursion -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/usr/local/opt/openssl/include -Wno-strict-aliasing
--   Build type        :   Debug
--
--   BUILD_docs        :   ON
--
-- Dependencies:
--   Linker flags      :
--   Boost             :   Yes (ver. 1.55)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.4.0)
--   LLVM              :   Yes (ver. 3.7.1)
--
-- Documentaion:
--   Doxygen           :   /usr/local/bin/doxygen (1.8.13)
--   config_file       :
--
-- Install:
--   Install path      :   /Users/tao/Cpp/peloton-master/build/install
--
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/tao/Cpp/peloton-master/build
```

```
➜  build make -j 4
[  0%] Running C++/Python protocol buffer compiler on /Users/tao/Cpp/peloton-master/src/proto/abstract_service.proto
[  0%] Running C++/Python protocol buffer compiler on /Users/tao/Cpp/peloton-master/src/proto/logging_service.proto
Scanning dependencies of target libpg_query
[  0%] Original libpg makefile target

.......

[ 95%] Building CXX object src/CMakeFiles/peloton.dir/type/value.cpp.o
[ 95%] Building CXX object src/CMakeFiles/peloton.dir/type/varlen_type.cpp.o
[ 95%] Building CXX object src/CMakeFiles/peloton.dir/util/string_util.cpp.o
[ 95%] Building CXX object src/CMakeFiles/peloton.dir/util/stringbox_util.cpp.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/murmur3/MurmurHash3.cpp.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/empirical_data.cc.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/hll.cc.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/hll_data.cc.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/utility.cc.o
[ 97%] Linking CXX shared library ../lib/libpeloton-d.dylib
[ 97%] Built target peloton
Scanning dependencies of target peloton-bin
[ 97%] Building CXX object src/CMakeFiles/peloton-bin.dir/main/peloton/peloton.cpp.o
[100%] Linking CXX executable ../bin/peloton
[100%] Built target peloton-bin
```

**Comment by seojungmin** [comment] 2017-09-26 04:50
Try `cmake -DCMAKE_PREFIX_PATH=`llvm-config-3.7 --prefix` -DCMAKE_BUILD_TYPE=release ..`.  This may not solve the problem, but in OSX, this PREFIX cmake option is required.

**Comment by apavlo** [comment] 2017-10-17 03:12
Duplicate of #824

**Comment by bluealert** [comment] 2017-10-22 08:16
@PauloAmora @seojungmin @apavlo 

I have found the reason and test it:

add `-Wno-sign-compare` after `-Werror` at: https://github.com/cmu-db/peloton/blob/master/CMakeLists.txt#L76

remove `SYSTEM` at: https://github.com/cmu-db/peloton/blob/master/test/CMakeLists.txt#L36

**Comment by apavlo** [comment] 2017-10-22 12:32
Can you send a PR with the fix so that you get credit for it?

**Comment by bluealert** [comment] 2017-10-22 17:03
@apavlo 

Hi, Professor, I have created a pull request: https://github.com/cmu-db/peloton/pull/853

I have test the modification on Mac(10.12.6, clang-800.0.42.1) and Ubuntu(16.04, gcc 5.4) successfully.

**Comment by poojanilangekar** [comment] 2017-12-20 20:37
We are not going to be merging this as discussed in #853

**Closed by poojanilangekar** 2017-12-20 20:37 UTC
