### ISSUE TITLE
Joins with more than three join partners segfault

### ISSUE THREAD

**Issue by mrks** [cmu-db/peloton#1195] opened 2018-03-07 17:33 UTC
On 0db1a2a478ce2102451a47c0be14ecb5ecb45e00 (current master), this causes a segfault:

```
test=# CREATE DATABASE test;
CREATE DATABASE
test=# CREATE TABLE a (x INTEGER);
CREATE TABLE
test=# CREATE TABLE b (x INTEGER);
CREATE TABLE
test=# CREATE TABLE c (x INTEGER);
CREATE TABLE
test=# CREATE TABLE d (x INTEGER);
CREATE TABLE
```

```
test=# SELECT * FROM a JOIN b ON a.x = b.x JOIN d ON a.x = d.x;
 x | x | x
---+---+---
(0 rows)
```

```
test=# SELECT * FROM a JOIN b ON a.x = b.x JOIN C ON a.x = c.x JOIN d ON a.x = d.x;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

In 5878dc7, this still works.

**Comment by pmenon** [comment] 2018-03-11 15:16
@mrks Thanks for reporting this!

@GustavoAngulo Looks like 7d083d546860ff91420cf56c5571b2abd340f004 (for #1150) is causing regression. Assigning to you to fix. 

@chenboy Can you co-ordinate a fix for this.

**Closed** 2018-04-02 22:45 UTC
Labels: bug
