### ISSUE TITLE
BwTree crashes when re-inserting deleted key

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#713] opened 2017-07-02 16:15 UTC
**I think that this bug is related to the same problem in #709. I don't think that we are cleaning up entries from the indexes properly.**

--------

First create a table with a single column and a primary key:
```
postgres=# CREATE TABLE foo (id INT PRIMARY KEY);
CREATE TABLE foo (id INT PRIMARY KEY) 0
postgres=# INSERT INTO foo VALUES (123);
INSERT INTO foo VALUES (123) 1
postgres=# SELECT * FROM foo;
 id  
-----
 123
(1 row)
```

Next we will delete the tuple from the table and execute a `SELECT` statement to show that it is empty:
```
postgres=# DELETE FROM foo;
DELETE FROM foo 1
postgres=# SELECT * FROM foo;
 id 
----
(0 rows)
```

Now let's try to insert that same tuple back into the table. This should succeed because the table is supposed to be empty:
```
postgres=# INSERT INTO foo VALUES (123);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Here is the assert message of the failure:
```
peloton: /home/pavlo/Documents/Peloton/Github/peloton-master/src/index/bwtree_index.cpp:106: \
bool peloton::index::BWTreeIndex<KeyType, ValueType, KeyComparator, KeyEqualityChecker, KeyHashFunc, ValueEqualityChecker, ValueHashFunc>::CondInsertEntry(const peloton::storage::Tuple*, peloton::ItemPointer*, std::function<bool(const void*)>) \
[with KeyType = peloton::index::CompactIntsKey<1ul>; ValueType = peloton::ItemPointer*; KeyComparator = peloton::index::CompactIntsComparator<1ul>; KeyEqualityChecker = peloton::index::CompactIntsEqualityChecker<1ul>; KeyHashFunc = peloton::index::CompactIntsHasher<1ul>; ValueEqualityChecker = peloton::ItemPointerComparator; ValueHashFunc = peloton::ItemPointerHashFunc]: \
Assertion `ret == true' failed.
```

Backtrace is attached.
[backtrace.txt](https://github.com/cmu-db/peloton/files/1117911/backtrace.txt)

**Comment by yingjunwu** [comment] 2017-07-03 08:59
Yes I agree that this is caused by the same problem as in #709.

**Comment by yingjunwu** [comment] 2017-07-24 05:35
fixed by #764

**Comment by pmenon** [comment] 2017-07-27 12:49
Let's not close the issue until the PR has been tested and merged in.

**Comment by yingjunwu** [comment] 2017-08-11 03:23
This issue can be closed as the PR has been merged and tested.

**Closed by yingjunwu** 2017-08-11 03:23 UTC
Labels: bug
