### ISSUE TITLE
TPCC fails on INSERT INTO OORDER

### ISSUE THREAD

**Issue by lishuomountain** [cmu-db/peloton#665] opened 2017-05-09 14:41 UTC
When I run TPCC benchmark, the sytstem crashed  with the following info: 

2017-05-09 22:23:07 [src/wire/packet_manager.cpp:391:ExecParseMessage] DEBUG - PrepareStatement[] => INSERT INTO OORDER (O_ID, O_D_ID, O_W_ID, O_C_ID, O_ENTRY_D, O_OL_CNT, O_ALL_LOCAL) VALUES ($1, $2, $3, $4, $5, $6, $7)
2017-05-09 22:23:07 [src/wire/packet_manager.cpp:391:ExecParseMessage] DEBUG - PrepareStatement[] => INSERT INTO OORDER (O_ID, O_D_ID, O_W_ID, O_C_ID, O_ENTRY_D, O_OL_CNT, O_ALL_LOCAL) VALUES ($1, $2, $3, $4, $5, $6, $7)
2017-05-09 22:23:07 [src/tcop/tcop.cpp:310:PrepareStatement] DEBUG - Statement Prepared: Statement[UNNAMED] -> **INSERT INTO OORDER (O_ID, O_D_ID, O_W_ID, O_C_ID, O_ENTRY_D, O_OL_CNT, O_ALL_LOCAL) VALUES ($1, $2, $3, $4, $5, $6, $7)** (TablesRef={33554539},ReplanNeeded=0, QueryType=INSERT)
**Message :: TIMESTAMP is not coercable to DECIMAL**
terminate called after throwing an instance of 'peloton::Exception'
  what():  TIMESTAMP is not coercable to DECIMAL
2017-05-09 22:23:07 [src/tcop/tcop.cpp:310:PrepareStatement] DEBUG - Statement Prepared: Statement[**UNNAMED**] -> INSERT INTO OORDER (O_ID, O_D_ID, O_W_ID, O_C_ID, O_ENTRY_D, O_OL_CNT, O_ALL_LOCAL) VALUES ($1, $2, $3, $4, $5, $6, $7) (TablesRef={33554539}, ReplanNeeded=0, QueryType=INSERT)
Aborted

The reason seems to the lost of the 8th field of the oorder table (i.e., o_entry_d timestamp).  Table oorder has 8 fields, but the insert statement only has 7 values as shown above.

**Comment by apavlo** [comment] 2017-05-09 14:43
@lishuomountain Are you using 'peloton' for your `dbtype` in your OLTP-Bench config file?

**Comment by lishuomountain** [comment] 2017-05-09 14:44
@apavlo  Yes!

**Comment by hzxa21** [comment] 2017-05-09 22:37
Same issue here. I think this is caused by binding parameters incorrectly in insert_plan.cpp. I can try to look into that later.

**Comment by apavlo** [comment] 2017-05-19 17:42
@hzxa21 I think this fell through the cracks at the end of the semester. We really need this fixed now. It's urgent. We can't test #672

**Closed** 2017-05-24 23:07 UTC
Labels: bug
