### ISSUE TITLE
TPC-C gets super slow when customer index is enabled

### ISSUE THREAD

**Issue by jessesleeping** [cmu-db/peloton#426] opened 2016-12-23 09:59 UTC
When we enable the customer index, TPC-C throughput drops dramatically and become not scalable at all.

**Comment by malin1993ml** [comment] 2016-12-26 05:02
@jessesleeping In the email you said you tried to allocate the key tuple’s varlen in the executor context varlen pool, instead of the index’s one. But the number is still really bad. I don't quite understand why the number is still really bad in this case. There's no contention here, since one executor context can only be used by a single execution thread at one time, right?

**Comment by jessesleeping** [comment] 2016-12-27 00:26
When using executor context's varlen pool, the number is bad but scalable. The problem is varlen pool itself is much slower than the plain malloc.

**Comment by jarulraj** [comment] 2016-12-27 00:36
Jiexi -- If we use a latch free per-connection pool, would the performance
improve?

Or do you think that a new implementation is needed? If so, what are the
key differences in its design with respect to the current one?

On Dec 27, 2016 5:57 AM, "Jiexi Lin" <notifications@github.com> wrote:

When using executor context's varlen pool, the number is bad but scalable.
The problem is varlen pool itself is much slower than the plain malloc.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cmu-db/peloton/issues/426#issuecomment-269251486>, or mute
the thread

**Comment by jessesleeping** [comment] 2016-12-27 01:11
I think per connection varlen pool or per thread varlen pool can help improve our performance in other cases (e.g. allocating varlen for inserted titles), but not the problem stated here. 

A lock free implementation may help when background gc is freeing memory in varlen pool while the worker thread is allocating memory in its local pool.

Small things we can do is to optimize the usage of std::list and bitmap in current implementation. I think @MattPerron and I have the feeling that they can be more efficient. But I think what we really need to do is to re-consider what we want from the varlen pool and how can we distinguish it from general purpose malloc implementation?

**Comment by MattPerron** [comment] 2016-12-27 15:21
"When using executor context's varlen pool, the number is bad but scalable. The problem is varlen pool itself is much slower than the plain malloc."

Then we should just use pure malloc in these cases.

"But I think what we really need to do is to re-consider what we want from the varlen pool and how can we distinguish it from general purpose malloc implementation?"

If we are going to re-implement Varlen Pool we should do it right from the ground up and fix all the problems we have found so far. 

Maybe I'm missing something but In my understanding the only thing Varlen pool gives us is the ability to separate memory that we allocate for temporary use (in the executor context) and memory that we allocate for the table itself. I'm not sure if there is a performance benefit to doing this, but presumably it would help the hardware prefetcher in cases like a sequential scan. If our implementation is always slower than JEMalloc, we should just be using malloc all the time. 

If we choose to keep the varlen pool, and not simply use jemalloc. I think it makes the most sense for the Table (not the tile or tilegroup) to have a pool per core. We would then remove all the synchronization from varlen pool (note that it would require that worker threads be pinned to cores). varlen pool also should be profiled in isolation to achieve the best performance. I suggest having a pools attached to the table because it then allows us to use @jessesleeping 's reference count optimization when copying tuples without worrying about potential future garbage collection issues when tilegroups are cleaned up.

As @jessesleeping suggested, we seem to be re-implementing malloc, maybe there is a way to implement varlen pool by taking advantage of JEMalloc's non-standard API to specify the "Arena" to allocate memory, and leaving the details of implementation to JEMalloc. An argument against this is if we change to another allocator in the future, we would have to reimplement the varlen pool. It may also be worth it to consider NUMA-awareness. JEMalloc's lack of NUMA-awareness is challenging to circumvent.

What are everyone's thoughts about this?

**Comment by MattPerron** [comment] 2016-12-27 15:22
This probably deserves a separate issue.

**Comment by apavlo** [comment] 2017-01-05 23:42
Fixed with #461 + #456

**Closed by apavlo** 2017-01-05 23:42 UTC
