### ISSUE TITLE
Segmentation fault when I use psql to run a SQL script

### ISSUE THREAD

**Issue by star013** [cmu-db/peloton#1049] opened 2018-01-11 05:17 UTC
Hi, there. I am a student who want to take 15721 in spring. I installed peloton in my local mac OS. When I tried to run a demo SQL script using psql as Wiki shows, peloton had segmentation fault.

I run peloton by typing command:
`peloton`
and I run psql by typing command:
`psql "sslmode=disable" -U postgres -h 127.0.0.1 -p 15721`
In psql terminal, I input the following command to run a SQL script:
`\i peloton/script/testing/join/nested_loop_join.sql`
However, psql shows,
`psql:peloton/script/testing/join/nested_loop_join.sql:14: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
psql:peloton/script/testing/join/nested_loop_join.sql:14: connection to server was lost`

I use lldb to track the error in peloton and it shows the following codes,
`2018-01-11 00:07:10 [src/network/network_manager.cpp:49:CreateNewConnection] INFO  - Create new connection: id = 4
2018-01-11 00:07:10 [src/network/network_manager.cpp:167:StartServer] INFO  - Listening on port 15721
2018-01-11 00:07:15 [src/network/network_manager.cpp:49:CreateNewConnection] INFO  - Create new connection: id = 17
2018-01-11 00:07:15 [src/network/network_connection.cpp:425:ProcessInitialPacket] INFO  - protocol version: 196608
2018-01-11 00:07:24 [src/codegen/table.cpp:92:GenerateScan] INFO  - Begin Looping over all tile groups
2018-01-11 00:07:24 [src/codegen/table.cpp:92:GenerateScan] INFO  - Begin Looping over all tile groups
2018-01-11 00:07:24 [src/codegen/util/bloom_filter.cpp:59:Init] INFO  - BloomFilter num_bits: 4745610 bits_per_element: 9.491220 num_hash_funcs: 1
Process 33756 stopped
* thread #2, stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
    frame #0: 0x000000010029448d libpeloton.0.0.5.dylib`peloton::optimizer::Optimizer::ChooseBestPlan(int, peloton::optimizer::PropertySet, std::__1::unordered_map<std::__1::shared_ptr<peloton::expression::AbstractExpression>, unsigned int, peloton::expression::ExprHasher, peloton::expression::ExprEqualCmp, std::__1::allocator<std::__1::pair<std::__1::shared_ptr<peloton::expression::AbstractExpression> const, unsigned int> > >*) + 237
libpeloton.0.0.5.dylib`peloton::optimizer::Optimizer::ChooseBestPlan:
->  0x10029448d <+237>: movq   0x8(%r14), %rdi
    0x100294491 <+241>: subq   (%r14), %rdi
    0x100294494 <+244>: movq   %rdi, %rbx
    0x100294497 <+247>: sarq   $0x2, %rbx
Target 0: (peloton) stopped.`

I do not know where is wrong. Could you give any suggestions?

Thanks.

**Comment by schedutron** [comment] 2018-01-14 17:26
Can you provide the contents of your `.sql` script?

**Comment by star013** [comment] 2018-01-14 17:31
Hi, @schedutron 

I just use the script in the "script" folder in the latest peloton. The relative path is `script/testing/join/nested_loop_join.sql`.

**Comment by pervazea** [comment] 2018-01-19 21:38
See the comment in #1070 
_When performing the commands one by one via the script, it appears that
SET ENABLE_MERGEJOIN TO FALSE;
causes the segfault._

**Comment by pervazea** [comment] 2018-02-08 14:24
Closing as a duplicate of #1131

**Closed by pervazea** 2018-02-08 14:24 UTC
