### ISSUE TITLE
Error running 'bash package.sh' on macOS High Sierra

### ISSUE THREAD

**Issue by DeanChensj** [cmu-db/peloton#1249] opened 2018-03-30 21:48 UTC
$ bash packages.sh
packages.sh: line 20: ${DISTRO^^}: bad substitution
Unknown distribution 'darwin'

Platform: Darwin Dean-Mac.wv.cc.cmu.edu 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Comment by pmenon** [comment] 2018-03-30 23:43
Odd, seems to work for me on 10.13.3. Can you also try `./packages.sh` ?

**Comment by DeanChensj** [comment] 2018-03-30 23:58
The error message is pretty much the same. I copied out the macOS part to another script and it works. Thanks!

**Comment by mbutrovich** [comment] 2018-03-31 04:34
Just as a sanity check I just spun up a clean 10.13.4 image and couldn't reproduce the issue.

**Comment by pmenon** [comment] 2018-03-31 14:00
And our macOS build run with this script. Closing for now.

**Closed by pmenon** 2018-03-31 14:00 UTC
