### ISSUE TITLE
Add support for "SELECT...FOR UPDATE"

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#224] opened 2016-08-31 19:28 UTC
The `ReadModifyWrite` transaction in YCSB uses the `FOR UPDATE` feature in the first SELECT query.

https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/ycsb/procedures/ReadModifyWriteRecord.java#L30

We currently support this in the new parser and are able to set the flag properly in the query plan, but we need to add code to take the write lock in the `IndexScanExecutor` and `SeqScanExecutor` components.

@jarulraj - You may need to add utility code to make it easier to grab the write lock for a tuple.

**Comment by apavlo** [comment] 2016-09-08 15:37
The basic idea of how this works is that there will be a boolean flag in the `IndexScanPlan` and `SeqScanPlan` plan node objects. If a tuple satisfies the predicate during the scan (and will be added in executor's output result), then you will want to acquire a write-lock. 

https://github.com/cmu-db/peloton/blob/master/src/executor/seq_scan_executor.cpp#L148
https://github.com/cmu-db/peloton/blob/master/src/executor/seq_scan_executor.cpp#L161

@yingjunwu  Would it be easier if we modify `TransactionManager.PerformRead()` to take in a boolean flag that tells the manager to acquire the lock?

@saifalharthi Where is the "FOR UPDATE" flag in the plan nodes? I only see it in the parser code.

**Comment by ranxian** [comment] 2016-09-08 15:52
@apavlo 
There is actually an `AcquireOwnership()`([link](https://github.com/cmu-db/peloton/blob/master/src/concurrency/timestamp_ordering_transaction_manager.cpp#L292)) method that takes a write lock. We can implement as you said to maintain a boolean flag and call this method

**Comment by yingjunwu** [comment] 2016-09-08 16:36
@apavlo I think current API is sufficient enough to implement `FOR UPDATE`. As @ranxian said, there's several APIs for acquiring read or write locks. `IsOwnable()` (https://github.com/cmu-db/peloton/blob/master/src/executor/update_executor.cpp#L112) checks whether the current transaction owns the write lock, and `AcquireOwnership()` (https://github.com/cmu-db/peloton/blob/master/src/executor/update_executor.cpp#L118) attempts to acquire the write lock. `YieldOwnership()` (https://github.com/cmu-db/peloton/blob/master/src/executor/update_executor.cpp#L157) helps release the write lock if the version insertion to indexes fails (e.g., violation of foreign key or unique index constraints).

**Comment by jarulraj** [comment] 2016-09-08 17:36
@apavlo I have already discussed this with @aquafemi and @kreichek.

**Comment by saifalharthi** [comment] 2016-09-08 17:54
@apavlo apparently this was not merged to master. I issued a PR containing that code.

**Comment by yingjunwu** [comment] 2016-09-08 18:08
@saifalharthi thanks for your PR. I think the PR modified the API of `IndexScanExecutor`, but @kreichek and @aquafemi still need to fill in the logic.

**Comment by saifalharthi** [comment] 2016-09-08 18:10
@yingjunwu I understand that , I did not change anything in `IndexScanExecutor`. I only added the flags to the planner so it can be used there.

**Comment by yingjunwu** [comment] 2016-09-08 18:14
@saifalharthi yes I saw that part. Let's merge your PR once it passes all the tests.

**Comment by saifalharthi** [comment] 2016-09-08 23:33
@yingjunwu I think the PR is ready to be merged. Only VarlenTest has a problem and I think Yuemei is trying to fix that

**Comment by apavlo** [comment] 2016-09-09 14:26
@kreichek @aquafemi There should be enough code now for you to complete this task. Be sure to write a test case that checks whether it works. This will take longer than the actual implementation but it's important.

The test case should create two txns. The first txn does a SELECT FOR UPDATE on a tuple and then wiats. The second txn tries to modify that same tuple but it should fail because of the conflict. You should do this by invoking the executors directly (i.e., you do not need to execute a SQL query and go through the parser/planner).

**Comment by kreichek** [comment] 2016-09-11 19:58
I will be looking to get this down early this week

**Comment by kreichek** [comment] 2016-09-14 01:03
Femi and I are working on implementing this. 

We are confused as how to the executors are called. We searched on both Github and Eclipse for instances of the many of the executors and didn't find any usages within the codebase. 

We have been looking through update_executor.cpp to get a sense of the code. What exactly does isOwner mean in the context of an update command (https://github.com/cmu-db/peloton/blob/4b8755cfc3b9d23968e67c75bae632b19814dc78/src/executor/update_executor.cpp#L98). Does it return true if our transaction currently has the lock or does it have a different meaning? In the case of for update, what should the behavior be if the tuple returns true for isOwner?

Our sense of the implementation is that for each tuple we will check if it isOwnable, if it is, we will acquire ownership, and return. How should we go about dealing with releasing ownership once the transaction is complete?

**Comment by apavlo** [comment] 2016-09-14 01:08
> Our sense of the implementation is that for each tuple we will check if it isOwnable, if it is, we will acquire ownership, and return. How should we go about dealing with releasing ownership once the transaction is complete?

The `TransactionManager` will do this for you automatically when the txn commits.

**Comment by saifalharthi** [comment] 2016-09-14 01:09
As for Executing the plan you can check https://github.com/cmu-db/peloton/blob/master/src/executor/plan_executor.cpp#L45

You can find calls for it in the test files and in
https://github.com/cmu-db/peloton/blob/master/src/tcop/tcop.cpp#L50

**Comment by apavlo** [comment] 2016-09-17 13:51
@aquafemi @kreichek Have you written test cases? Do you guys need somebody to code review this yet?

**Comment by aquafemi** [comment] 2016-09-17 21:24
We were working on it yesterday. We tried to emulate the update_test and I think the problem is that going that way requires going through the parser/planner which you advised against.

* Does the table need to be prepopulated with some tuples to run the test case?
* How do we invoke the executor directly? We were thinking of using the TransactionScheduler in the transaction_tests_utill to schedule the two transactions for the test case but aren't sure how to tie in the for_update executor.

**Comment by apavlo** [comment] 2016-09-17 21:32
> Does the table need to be prepopulated with some tuples to run the test case?

Yes, otherwise there is nothing to lock.

> How do we invoke the executor directly? We were thinking of using the TransactionScheduler in the transaction_tests_utill to schedule the two transactions for the test case but aren't sure how to tie in the for_update executor.

If you look at `UpdateTests`, you will see that it uses the parser/planner to generate a query plan but then it invokes the plan on its own:

https://github.com/cmu-db/peloton/blob/master/test/executor/update_test.cpp#L123

It's actually not a well-written test case because it doesn't actually check whether the values in the tuples are correct. Your test case should do the steps that I describe above but make sure that you check that the end state of the database is as you expect it.

**Comment by apavlo** [comment] 2016-09-21 12:50
@aquafemi We should meet to discuss this task.

**Comment by apavlo** [comment] 2016-10-10 13:53
@jessesleeping - Can you finish this task real quick this week and get it into the master? Please be sure to add a test case.

**Comment by jessesleeping** [comment] 2016-10-10 14:47
Sure.

**Comment by malin1993ml** [comment] 2016-10-11 20:42
#305 was a hacking for us to profile TPC-C first without supporting this. Please remove that after this is done.

**Comment by malin1993ml** [comment] 2016-10-14 20:16
Done by #308.

**Closed by malin1993ml** 2016-10-14 20:16 UTC
