### ISSUE TITLE
Segfault running script/testing/join/nested_loop_join.sql

### ISSUE THREAD

**Issue by nappelson** [cmu-db/peloton#1070] opened 2018-01-19 00:59 UTC
> nappelson@Nathans-MacBook-Air ~/dev/peloton (master) $ peloton -port 5432
2018-01-18 19:53:59 [src/network/network_manager.cpp:49:CreateNewConnection] INFO  - Create new connection: id = 4
2018-01-18 19:53:59 [src/network/network_manager.cpp:167:StartServer] INFO  - Listening on port 5432
2018-01-18 19:54:06 [src/network/network_manager.cpp:49:CreateNewConnection] INFO  - Create new connection: id = 17
2018-01-18 19:54:06 [src/network/network_connection.cpp:425:ProcessInitialPacket] INFO  - protocol version: 196608
Segmentation fault: 11

When performing the commands one by one via the script, it appears that
`SET ENABLE_MERGEJOIN TO FALSE;
`
causes the segfault.

**Comment by schedutron** [comment] 2018-01-19 12:26
Yes, this is identical to #1049.

**Comment by pervazea** [comment] 2018-01-19 21:38
Duplicate of #1049. Closing this one.

**Closed by pervazea** 2018-01-19 21:38 UTC
Labels: testing
