### ISSUE TITLE
Support IN in where clause

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/peloton#561] opened 2017-03-03 22:39 UTC
```sql
postgres=# create table a(id int, value varchar);
create table a(id int, value varchar) 0
postgres=# insert into a values(1, 'hi');
insert into a values(1, 'hi') 1
postgres=# select * from a;
 id | value 
----+-------
  1 | hi
(1 row)

postgres=# select * from a where id in (1);
Error parsing SQL statement
```

**Comment by poojanilangekar** [comment] 2017-12-21 15:47
Duplicate of #568

**Closed by poojanilangekar** 2017-12-21 15:47 UTC
Labels: enhancement
