### ISSUE TITLE
SEG FAULT when typing wrong 'SELECT'

### ISSUE THREAD

**Issue by ChTimTsubasa** [cmu-db/peloton#680] opened 2017-05-24 21:36 UTC
The program crashes and gives no other information in DEBUG mode when typing SELECT query without specifying the tuple that is queried for. 

The information printed on the console is:
2017-05-24 17:35:43 [src/wire/libevent_callbacks.cpp:46:WorkerHandleNewConn] DEBUG - Creating new socket fd:27
2017-05-24 17:35:43 [src/wire/libevent_server.cpp:53:CreateNewConn] INFO  - create new connection: id = 27
2017-05-24 17:35:43 [src/wire/packet_manager.cpp:65:PacketManager] DEBUG - Registered new PacketManager [count=2]
Segmentation fault (core dumped)

Those crash-causing queries examples including but (may) not be limited to: "SELECT;", "SELECT FROM <TABLE_NAME>;", etc.

Other invalid query strings such as "CREATE;”, " INSERT;" can be recognized and works well.

**Comment by haojin2** [comment] 2017-05-24 21:45
Would you please rerun it with gdb and provide the backtrace for the segfault?

**Comment by ChTimTsubasa** [comment] 2017-05-25 03:40
Thread 4 "peloton" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffccfff700 (LWP 3435)]
0x00007ffff6917d11 in peloton::parser::PostgresParser::TargetTransform (
    root=0x0)
    at /home/tim/Documents/project/peloton/src/parser/postgresparser.cpp:496
496	  for (auto cell = root->head; cell != nullptr; cell = cell->next) {
(gdb) backtrace
#0  0x00007ffff6917d11 in peloton::parser::PostgresParser::TargetTransform (
    root=0x0)
    at /home/tim/Documents/project/peloton/src/parser/postgresparser.cpp:496
#1  0x00007ffff691af4b in peloton::parser::PostgresParser::SelectTransform (
    root=0x7fffca438628)
    at /home/tim/Documents/project/peloton/src/parser/postgresparser.cpp:1078
#2  0x00007ffff691b441 in peloton::parser::PostgresParser::NodeTransform (
    stmt=0x7fffca438628)
    at /home/tim/Documents/project/peloton/src/parser/postgresparser.cpp:1142
#3  0x00007ffff691b6a6 in peloton::parser::PostgresParser::ListTransform (
    root=0x7fffca438758)
    at /home/tim/Documents/project/peloton/src/parser/postgresparser.cpp:1198
#4  0x00007ffff691bade in peloton::parser::PostgresParser::ParseSQLString (
    text=0x7fffccffea50 "SELECT")
    at /home/tim/Documents/project/peloton/src/parser/postgresparser.cpp:1252
#5  0x00007ffff691bb42 in peloton::parser::PostgresParser::ParseSQLString (
    sql="SELECT")
    at /home/tim/Documents/project/peloton/src/parser/postgresparser.cpp:1260
#6  0x00007ffff691bc05 in peloton::parser::PostgresParser::BuildParseTree (
    this=0x7ffff7dc9388 <peloton::parser::PostgresParser::GetInstance()::parser>, query_string="SELECT")
    at /home/tim/Documents/project/peloton/src/parser/postgresparser.cpp:1270
#7  0x00007ffff6977264 in peloton::tcop::TrafficCop::PrepareStatement (
---Type <return> to continue, or q <return> to quit---
    this=0x7fffca419080, statement_name="unnamed", query_string="SELECT", 
    error_message="")
    at /home/tim/Documents/project/peloton/src/tcop/tcop.cpp:286
#8  0x00007ffff69769d3 in peloton::tcop::TrafficCop::ExecuteStatement (
    this=0x7fffca419080, query="SELECT", 
    result=std::vector of length 0, capacity 0, 
    tuple_descriptor=std::vector of length 0, capacity 0, 
    rows_changed=@0x7fffccffe978: 0, error_message="", thread_id=0)
    at /home/tim/Documents/project/peloton/src/tcop/tcop.cpp:149
#9  0x00007ffff69d4f19 in peloton::wire::PacketManager::ExecQueryMessage (
    this=0x7fffca40f2a0, pkt=0x7fffca40f510, thread_id=0)
    at /home/tim/Documents/project/peloton/src/wire/packet_manager.cpp:328
#10 0x00007ffff69d938f in peloton::wire::PacketManager::ProcessPacket (
    this=0x7fffca40f2a0, pkt=0x7fffca40f510, thread_id=0)
    at /home/tim/Documents/project/peloton/src/wire/packet_manager.cpp:895
#11 0x00007ffff69bfd2b in peloton::wire::StateMachine (conn=0x7fffca40f280)
    at /home/tim/Documents/project/peloton/src/wire/libevent_callbacks.cpp:157
#12 0x00007ffff69bf94f in peloton::wire::EventHandler (connfd=27, ev_flags=2, 
    arg=0x7fffca40f280)
    at /home/tim/Documents/project/peloton/src/wire/libevent_callbacks.cpp:73
#13 0x00007ffff4090420 in event_base_loop ()
   from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#14 0x00007ffff69c8b00 in peloton::wire::LibeventMasterThread::StartWorker (
---Type <return> to continue, or q <return> to quit---
    worker_thread=0x7fffed2af300)
    at /home/tim/Documents/project/peloton/src/wire/libevent_thread.cpp:74
#15 0x00007ffff69d069a in std::_Bind_simple<void (*(peloton::wire::LibeventWorkerThread*))(peloton::wire::LibeventWorkerThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x7fffed3b8128) at /usr/include/c++/5/functional:1531
#16 0x00007ffff69d0420 in std::_Bind_simple<void (*(peloton::wire::LibeventWorkerThread*))(peloton::wire::LibeventWorkerThread*)>::operator()() (
    this=0x7fffed3b8128) at /usr/include/c++/5/functional:1520
#17 0x00007ffff69d0128 in std::thread::_Impl<std::_Bind_simple<void (*(peloton::wire::LibeventWorkerThread*))(peloton::wire::LibeventWorkerThread*)> >::_M_run() (this=0x7fffed3b8110) at /usr/include/c++/5/thread:115
#18 0x00007ffff2ea68f0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007ffff493e6ca in start_thread (arg=0x7fffccfff700)
    at pthread_create.c:333
#20 0x00007ffff260c0af in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

**Comment by haojin2** [comment] 2017-05-25 03:56
I guess this is due to that libpg_query is not reporting an error on queries like "SELECT;". I think if you simply add "if (root == nullptr) return nullptr;" to the beginning of TargetTransform function this will be properly handled.

**Comment by ChTimTsubasa** [comment] 2017-05-26 00:20
Still not solving the problem.
After looking into the code, there are still problems left from:
https://github.com/cmu-db/peloton/blob/master/src/parser/postgresparser.cpp#L1073

Even after fixing the TargetTransform() and FromTransform() by adding the nullptr detection, the program still gives SEG_FAULT coming from files without source code, since gdb is giving only machine code positions.

Probably we should detect the error at the beginning of SelectTransform()?

Besides, I am not able to locate the line that calls the SEGFAULT function since it seems no way to put a breakpoint in gdb due to compiling issue.

**Comment by haojin2** [comment] 2017-05-26 00:28
If libpg_query does not identify this as an illegal query then it will return a parsetree and our transformer will then transform any available parts in it, so this is a problem with libpg_query. On our side, to handle this case we may need to add additional checking to see if the transformed peloton parsetree has all nullptr for every single subpart of it.

**Comment by haojin2** [comment] 2017-05-26 00:32
To check what libpg_query returns for this kind of query, you can enable the debug output by visiting the third_party/libpg_query and uncomment the debug printing line. If that give an empty parse tree instead of an error message then it means the problem is in libpg_query.

**Comment by haojin2** [comment] 2017-05-26 05:34
So I just verified this on my own laptop and I found that libpg_query is giving back a Postgres parse tree like this: [{"SelectStmt": {"op": 0}}]. So my guess is correct that libpg_query does not think that this is an illegal query. I guess the solution is to check the target is not null after the transform. Or we can do it in TargetTransform, instead of returning a nullptr we can throw an exception.

**Comment by apavlo** [comment] 2017-07-02 17:25
@ChTimTsubasa This issue was fixed in #681, right?

**Comment by ChTimTsubasa** [comment] 2017-07-04 17:01
I am afraid not. But it can be fixed fast. I would open a new PR.

**Closed** 2017-07-14 18:23 UTC
