### ISSUE TITLE
Creating a table which already exists fails silently

### ISSUE THREAD

**Issue by MattPerron** [cmu-db/peloton#327] opened 2016-11-01 01:01 UTC
```
matt=# create table foo (blah1 INTEGER, blah2 INTEGER);
create table foo (blah1 INTEGER, blah2 INTEGER) 0
matt=# create table foo (blah1 INTEGER, blah2 INTEGER);
create table foo (blah1 INTEGER, blah2 INTEGER) 0
matt=# create table foo (blah1 INTEGER, blah2 INTEGER, blah3 INTEGER);
create table foo (blah1 INTEGER, blah2 INTEGER, blah3 INTEGER) 
matt=# select * from foo;
 blah1 | blah2 
-------+-------
(0 rows)

matt=# create table foo (blah1 INTEGER, blah2 INTEGER);
create table foo (blah1 INTEGER, blah2 INTEGER) 0
matt=# 
```

**Comment by poojanilangekar** [comment] 2017-12-20 19:57
@apavlo We now segfault on it. Will @haoxianghua's PR fix this? Or do you want me to take a look at it?

**Comment by poojanilangekar** [comment] 2017-12-20 22:37
Duplicate of #903

**Closed by poojanilangekar** 2017-12-20 22:37 UTC
